/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import modelo.Administrador;

/**
 *
 * @author rca29
 */
public class AdministradorGestionUsuario extends javax.swing.JFrame {

    /**
     * Creates new form AdministradorGestionUsuario
     */
    public AdministradorGestionUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbladmusuario = new javax.swing.JLabel();
        lbladmalta = new javax.swing.JLabel();
        lbladmmodificacion = new javax.swing.JLabel();
        lbladmbaja = new javax.swing.JLabel();
        btnadmalta = new javax.swing.JButton();
        btnadmmodificacion = new javax.swing.JButton();
        btnusubaja = new javax.swing.JButton();
        btnlecmodificacion = new javax.swing.JButton();
        btnlecalta = new javax.swing.JButton();
        btncomalta = new javax.swing.JButton();
        btncommodificacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbladmusuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbladmusuario.setText("Gestión de usuarios");

        lbladmalta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbladmalta.setText("Alta");

        lbladmmodificacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbladmmodificacion.setText("Modificación");

        lbladmbaja.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbladmbaja.setText("Baja");

        btnadmalta.setText("Administrador");
        btnadmalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadmaltaActionPerformed(evt);
            }
        });

        btnadmmodificacion.setText("Administrador");
        btnadmmodificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadmmodificacionActionPerformed(evt);
            }
        });

        btnusubaja.setText("Usuario");
        btnusubaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusubajaActionPerformed(evt);
            }
        });

        btnlecmodificacion.setText("Lector");
        btnlecmodificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlecmodificacionActionPerformed(evt);
            }
        });

        btnlecalta.setText("Lector");
        btnlecalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlecaltaActionPerformed(evt);
            }
        });

        btncomalta.setText("Común");

        btncommodificacion.setText("Común");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(lbladmusuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbladmalta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnadmalta)
                                    .addComponent(btnadmmodificacion))
                                .addGap(100, 100, 100)))))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnlecalta)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnlecmodificacion)
                                .addComponent(lbladmmodificacion)
                                .addComponent(btnusubaja)))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btncomalta)
                            .addComponent(btncommodificacion))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbladmbaja)
                        .addGap(176, 176, 176))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbladmusuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbladmalta)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadmalta)
                    .addComponent(btnlecalta)
                    .addComponent(btncomalta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(lbladmmodificacion)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadmmodificacion)
                    .addComponent(btnlecmodificacion)
                    .addComponent(btncommodificacion))
                .addGap(18, 18, 18)
                .addComponent(lbladmbaja)
                .addGap(21, 21, 21)
                .addComponent(btnusubaja)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnadmaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadmaltaActionPerformed
Administrador admin = new Administrador ();
new AltaAdministrador.setVisible(true);
this.dispose();

    }//GEN-LAST:event_btnadmaltaActionPerformed

    private void btnadmmodificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadmmodificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnadmmodificacionActionPerformed

    private void btnusubajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusubajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnusubajaActionPerformed

    private void btnlecmodificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlecmodificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlecmodificacionActionPerformed

    private void btnlecaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlecaltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlecaltaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorGestionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorGestionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorGestionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorGestionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorGestionUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadmalta;
    private javax.swing.JButton btnadmmodificacion;
    private javax.swing.JButton btncomalta;
    private javax.swing.JButton btncommodificacion;
    private javax.swing.JButton btnlecalta;
    private javax.swing.JButton btnlecmodificacion;
    private javax.swing.JButton btnusubaja;
    private javax.swing.JLabel lbladmalta;
    private javax.swing.JLabel lbladmbaja;
    private javax.swing.JLabel lbladmmodificacion;
    private javax.swing.JLabel lbladmusuario;
    // End of variables declaration//GEN-END:variables
}
